title: Matt Miller
description: Stuff that I come across and find interesting.
author: Matt Miller
email: mattmiller0989@gmail.com
phone: (713) 444-9947
github: https://github.com/mattmiller1989
about: I am Junior Computer Science Major at The University of Missouri Kansas City. I love using the power of programming to solve modern-day problems.
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/matmil89"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/matt-miller-557428172/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/mattmiller1989"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://mattmiller1989.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
